import Head from 'next/head';
import { BsFillMoonStarsFill } from "react-icons/bs";
import {AiFillLinkedin, AiFillInstagram, AiFillGithub } from 'react-icons/ai'
import Image from 'next/image';
import html from '../public/html.png';
import css from '../public/css.png';
import react from '../public/react.png';
import foto from '../public/foto.png';
import fitnew from '../public/fitnew.png';
import aluroni from '../public/aluroni.png';
import cronometro from '../public/cronometro.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState (false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Portfólio - Caio Assaoka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <main className="bg-white px-10 dark:bg-gray-900 md-px-20 lg-px-40"> 
        <section className= "min-h-screen	" >
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className=" text-xl font-burtons">Caio Assaoka - Dev</h1>
            <ul className="flex items-center">
              <li> <BsFillMoonStarsFill onClick={() => setDarkMode (!darkMode)} 
              className="cursor-pointer text-2xl" /> </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Caio Assaoka</h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">Front-End Developer</h3>
            <p className="text-lg py-5 leading-8 text-gray-800 dark:text-gray-200 
            md:text-xl mx-w-xl mx-auto">Desenvolvedor React, entusiasta em aprender o máximo a cada dia. Buscando desafios e oportunidades para me 
              desenvolver como profissional.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/caio-fernando-franco-da-silva-assaoka-01a236252/"><AiFillLinkedin/></a>
            <a href="https://github.com/CaioAssaoka"><AiFillGithub/></a>
            <a href="https://www.instagram.com/cahffs/"><AiFillInstagram/></a>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-100 md:w-100">
              <Image src={foto} layout="fill" objectFit="cover" />
            </div>
            </section>
            <section>
          <div className="text-center p-10">
            <h3 className="text-4xl py-2 dark:text-white">Oportunidades que procuro:</h3>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
              Oportunidades de desenvolvedor Front-End, de forma remota ou presencial em São Paulo - Capital (ou cidades
              próximas). Também aceito trabalho como freelancer (remoto).
            </p>
          </div>
          <div className="flex" >
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white">
              <Image src={html} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">HTML5</h3>
              <p py-2 >
                Estruturação das páginas feita em HTML5!
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white">
              <Image src={css} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">CSS3</h3>
              <p py-2 >
                Estilização das páginas web utilizando CSS3. Conhecimentos em SASS, CSS modules,
                Bootstrap e Tailwind 
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white">
              <Image src={react} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">ReactJS</h3>
              <p py-2 >
                Javascript feito com a biblioteca mais utilizada no mercado de trabalho. Conhecimentos em Typescript.
              </p>
            </div>
          </div>  
        </section>        
        <section className="py-10">
          <div className="text-center">
            <h3 className="text-5xl py-5 dark:text-white">Portfólio</h3>
             <p  className="text-2xl py-2 leading-8 text-gray-800 dark:text-gray-200"> Abaixo estão alguns projetos que fiz desde o começo da minha jornada. Alguns realizados em cursos 
              mas em sua grande maioria são projetos pessoais.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row " >
            <div className="basis-1/6 flex-1" >
              <a href="https://fit-dno3cqqn8-caioassaoka.vercel.app/">
                <Image src={fitnew} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/>
                </a>
            </div>
            <div className="basis-1/6 flex-1" >
              <a href="https://6327c34cc049e42efff9472c--admirable-pegasus-6823db.netlify.app/">
                <Image src={aluroni}
                 className="rounded-lg object-cover" 
                 width={"100%"} 
                 height={"100%"} 
                 layout="responsive"/>
                </a>
            </div>
            <div className="basis-1/6 flex-1" >
              <a href="https://cronometro-estudos-zeal.vercel.app/">
                <Image src={cronometro} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/>
                </a>
            </div>
          </div>
          <div className="text-center py-10 ">
          <h3 className="text-5xl py-5 dark:text-white">Descrição dos projetos:</h3>
          <div className="flex dark:text-white ">
          <div>
          <h3 className="text-lg font-medium pt-8 pb-2 flex-1">FitNew</h3>
          <p py-2>Projeto de um E-commerce utilizando ReactJS, Styled components, MUI-Material e
          React Router Dom</p>
          </div>
          <div>
          <h3 className="text-lg font-medium pt-8 pb-2 flex-1">Aluroni</h3>
          <p py-2>Projeto de um site de restaurante usando Typescript, Classnames e SASS</p>
          </div>
          <div>
          <h3 className="text-lg font-medium pt-8 pb-2 flex-1">Cronômetro de Estudos</h3>
          <p py-2>Meu primeiro projeto em React, um cronômetro de estudos</p>
          </div>
          </div>
          </div>

        </section>
        
       </main>
      </div>
    )
  }
